---
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    assignees: [AlekSi]
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "01:32"
